# Generated by Django 4.0.3 on 2022-03-16 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='NIT',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='Telefono',
            field=models.CharField(max_length=15),
        ),
    ]
