# Generated by Django 4.0.3 on 2022-03-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_empresa_nit_alter_empresa_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='NIT',
            field=models.CharField(max_length=15),
        ),
    ]
